spring.application.name=Velocity
spring.datasource.url=jdbc:mariadb://${CLOUDCORE_DB_HOST}:${CLOUDCORE_DB_PORT}/${CLOUDCORE_DB_NAME}
spring.datasource.username=${CLOUDCORE_DB_USER}
spring.datasource.password=${CLOUDCORE_DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update