import {
    FaBalanceScale,
    FaCss3Alt,
    FaDatabase, FaDocker,
    FaFile,
    FaFileAlt,
    FaFileArchive,
    FaFileAudio,
    FaFileCode,
    FaFileCsv, FaFileExcel, FaFileImage,
    FaFilePdf, FaFilePowerpoint, FaFileWord, FaFolder, FaGitAlt,
    FaHtml5,
    FaJava, FaJs, FaMarkdown, FaPhp, FaPython, FaReact, FaSass,
    FaTerminal, FaVuejs
} from "react-icons/fa";
import type {IconBaseProps} from "react-icons";
import React from "react";
import {SiC, SiCplusplus, SiGo, SiGradle, SiKotlin, SiRust, SiSvelte, SiTypescript} from "react-icons/si";
import { DiGroovy } from "react-icons/di";
import {VscTerminalPowershell} from "react-icons/vsc";
import { FaFileVideo } from "react-icons/fa6";

type IconMap = {
    [key: string]: React.ReactElement;
}

// Gigantic File Icon Map (generated by ChatGPT)
const fileIconMap: IconMap = {
    // Java
    "*.java": <FaJava />,
    "*.jar": <FaJava />,

    // Config
    ".cloudcore.conf": <FaFileCode />,
    "*.json": <FaFileCode />,
    "*.json5": <FaFileCode />,
    "*.yml": <FaFileCode />,
    "*.yaml": <FaFileCode />,
    "*.toml": <FaFileCode />,
    "*.ini": <FaFileCode />,
    "*.conf": <FaFileCode />,
    "*.cfg": <FaFileCode />,
    "*.properties": <FaFileAlt />,
    "*.env": <FaFileCode />,
    ".env": <FaFileCode />,

    // Web
    "*.html": <FaHtml5 />,
    "*.htm": <FaHtml5 />,
    "*.css": <FaCss3Alt />,
    "*.scss": <FaSass />,
    "*.sass": <FaSass />,
    "*.js": <FaJs />,
    "*.mjs": <FaJs />,
    "*.cjs": <FaJs />,
    "*.ts": <SiTypescript />,
    "*.tsx": <SiTypescript />,
    "*.jsx": <FaReact />,
    "*.vue": <FaVuejs />,
    "*.svelte": <SiSvelte />,

    // Backend / Sonstiges
    "*.kt": <SiKotlin />,
    "*.kts": <SiKotlin />,
    "*.groovy": <DiGroovy />,
    "*.gradle": <SiGradle />,
    "*.xml": <FaFileCode />,
    "*.sql": <FaDatabase />,

    // C/C++
    "*.c": <SiC />,
    "*.h": <SiC />,
    "*.cpp": <SiCplusplus />,
    "*.cc": <SiCplusplus />,
    "*.cxx": <SiCplusplus />,
    "*.hpp": <SiCplusplus />,
    "*.hh": <SiCplusplus />,

    // Rust / Go / Python / PHP
    "*.rs": <SiRust />,
    "*.go": <SiGo />,
    "*.py": <FaPython />,
    "*.php": <FaPhp />,

    // Shell
    "*.sh": <FaTerminal />,
    "*.bash": <FaTerminal />,
    "*.zsh": <FaTerminal />,
    "*.ps1": <VscTerminalPowershell />,

    // Markdown / Text
    "*.md": <FaMarkdown />,
    "*.txt": <FaFileAlt />,
    "LICENSE": <FaBalanceScale />,
    "README.md": <FaMarkdown />,

    // Images
    "*.png": <FaFileImage />,
    "*.jpg": <FaFileImage />,
    "*.jpeg": <FaFileImage />,
    "*.gif": <FaFileImage />,
    "*.webp": <FaFileImage />,
    "*.svg": <FaFileImage />,
    "*.ico": <FaFileImage />,

    // Audio
    "*.mp3": <FaFileAudio />,
    "*.wav": <FaFileAudio />,
    "*.ogg": <FaFileAudio />,
    "*.flac": <FaFileAudio />,

    // Video
    "*.mp4": <FaFileVideo />,
    "*.mkv": <FaFileVideo />,
    "*.avi": <FaFileVideo />,
    "*.mov": <FaFileVideo />,
    "*.webm": <FaFileVideo />,

    // Dokumente
    "*.pdf": <FaFilePdf />,
    "*.doc": <FaFileWord />,
    "*.docx": <FaFileWord />,
    "*.xls": <FaFileExcel />,
    "*.xlsx": <FaFileExcel />,
    "*.ppt": <FaFilePowerpoint />,
    "*.pptx": <FaFilePowerpoint />,
    "*.csv": <FaFileCsv />,

    // Archive
    "*.zip": <FaFileArchive />,
    "*.tar": <FaFileArchive />,
    "*.gz": <FaFileArchive />,
    "*.bz2": <FaFileArchive />,
    "*.xz": <FaFileArchive />,
    "*.7z": <FaFileArchive />,
    "*.rar": <FaFileArchive />,

    // Docker
    "Dockerfile": <FaDocker />,
    "docker-compose.yml": <FaDocker />,
    "docker-compose.yaml": <FaDocker />,

    // Git
    ".gitignore": <FaGitAlt />,
    ".gitattributes": <FaGitAlt />,
    ".gitmodules": <FaGitAlt />,
};


const folderIconMap : IconMap = {
    ".git": <FaGitAlt/>
}

export function getFileIcon(fileName: string, props: IconBaseProps = {}): React.ReactElement {
    for (const pattern in fileIconMap) {
        if (matches(pattern, fileName)) {
            return React.cloneElement(fileIconMap[pattern], props);
        }
    }
    return <FaFile {...props}/>;
}

export function getFolderIcon(folderName: string, props: IconBaseProps = {}): React.ReactElement {
    for (const pattern in folderIconMap) {
        if (matches(pattern, folderName)) {
            return React.cloneElement(folderIconMap[pattern], props);
        }
    }
    return <FaFolder {...props}/>;
}

function matches(pattern: string, text: string): boolean {
    const regex = new RegExp(
        "^" +
        pattern
            .replace(/[.+?^${}()|[\]\\]/g, "\\$&") // Regex-Sonderzeichen escapen
            .replace(/\*/g, ".*")                 // * -> beliebig viele Zeichen
        + "$"
    );

    return regex.test(text);
}
